### ISSUE TITLE
Colored STL

### ISSUE THREAD

**Issue by mkantz84** [chiedolabs/react-stl-viewer#24]
Hi,
I have a binary STL colored file.
Is there any way to show the file with its colors and without giving a `modelColor`?

**Comment by mkantz84** [comment]
Actually i found a solution and i'm going to PR it...

**Comment by jeangovil** [comment]
@mkantz84 Are you sure your colored file is in STL format? STL files don't save colors.

**Comment by mkantz84** [comment]
> @mkantz84 Are you sure your colored file is in STL format? STL files don't save colors.

There is a way to add colors to an STL file through its binary.
For example, from the three.js official site: https://threejs.org/examples/models/stl/binary/colored.stl

**Comment by mkantz84** [comment]
Now its working for me, but only locally. PR #25. Hope it will be merged..
