### ISSUE TITLE
CORS limitation

### ISSUE THREAD

**Issue by asafge** [chiedolabs/react-stl-viewer#3]
Hi,
The CORS limitation can be avoided, this is mostly depending on the server's CORS configuration which might allow all origins to access the file.

On the client side, the THREE.js loaders actually support this, but needs to have an attribute set:
In STLViewer.js, right after: `let loader = new THREE.STLLoader();`, Setting `loader.crossOrigin = '';`, allows loading external STL files.

I'm not if this should be set using an optional parameter or is this OK as a default, but anyway it works and removes the same origin limitation, as long as the server is configured correctly.

Would love to hear your thoughts on this.
Thanks!

**Comment by chiedo** [comment]
Awesome thinking!

I can't see any harm in adding it as a default.

If the server doesn't permit it, it won't work anyways.

If you're in favor, I'll go ahead and add it (unless you'd rather do a PR)!

Thanks for all your contributions recently!

**Comment by asafge** [comment]
@chiedo Sure, thanks for the fast merges :)

**Comment by ostapch** [comment]
@chiedo So if CORS restrictions fixed here, and I still have CORS errors when trying to load from another resource, does it mean that I should resolve problem on server?

**Comment by chiedo** [comment]
@ostapch correct! :)
