### ISSUE TITLE
React 16

### ISSUE THREAD

**Issue by ostapch** [chiedolabs/react-stl-viewer#9]
Hi, @chiedo .
What do you think about supporting latest react version? Also halogen library with loaders freezed and doesn't support it.
I can do PR if you don't mind

**Comment by chiedo** [comment]
That sounds great to me @ostapch 

Thanks!

**Comment by kopfnuss** [comment]
Hi @ostapch! 
Did you already have a go at this? I've noticed that the two main issues seem to be that react-stl-viewer as well as halogen are using React.propTypes instead of prop-types (I only briefly tested though).

**Comment by chiedo** [comment]
Hey @sonsoleslp I wasn't planning on doing so if I'm being honest, but I will now that you've brought it to my attention! I'm no longer working on the project I built this for so it's fallen to the back of mind.

**Comment by sonsoleslp** [comment]
That'd be great! I was planning on using it for a project and maybe even contribute to your library if it falls short of my requirements.

**Comment by sonsoleslp** [comment]
Thank you so much @chiedo !
